name: Microservices CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # ===== BUILD JARS =====

      - name: Build Eureka Server
        run: mvn clean package -DskipTests
        working-directory: service-registry/service-registry

      - name: Build User Service
        run: mvn clean package -DskipTests
        working-directory: user-service/user-service

      - name: Build Order Service
        run: mvn clean package -DskipTests
        working-directory: order-service/order-service

      - name: Build API Gateway
        run: mvn clean package -DskipTests
        working-directory: api-gateway/api-gateway

      # ===== DOCKER LOGIN =====

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # ===== BUILD & PUSH IMAGES =====

      - name: Build & Push Eureka Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/service-registry:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/service-registry:latest
        working-directory: service-registry/service-registry

      - name: Build & Push User Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/user-service:latest
        working-directory: user-service/user-service

      - name: Build & Push Order Service Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/order-service:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/order-service:latest
        working-directory: order-service/order-service

      - name: Build & Push API Gateway Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
        working-directory: api-gateway/api-gateway
